services:
  db:
    image: pgvector/pgvector:pg17 # Official image with vector support
    container_name: news_db
    ports:
      - "4646:5432"
    environment:
      POSTGRES_USER: news_admin
      POSTGRES_PASSWORD: news_adminPW
      POSTGRES_DB: news_db
      TZ: Asia/Hong_Kong
    volumes:
      - ./server/db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data   
  rsshub:
      image: diygod/rsshub
      restart: always
      ports:
        - "1200:1200"
      environment:
        NODE_ENV: production
        CACHE_TYPE: redis
        REDIS_URL: redis://redis:6379
  redis:
      image: redis:alpine
volumes:
  postgres_data: